### ISSUE TITLE
Investegate the need for a KB(Knowledge base)

### ISSUE THREAD

**Issue by Hortlund** [Linda-Carlstad/admin.lindacarlstad.se#23]
An idea that a knowledge base that is put under the admin subdomain to document different SOP (Standard Operating Procedure) for the different roles in the board, and for the new platform we built. Things that needs to be done, things that is good to know, and just all around how to handle stuff that might come up. You can create categories and then under them write SOP articles about all these stuff so future students will have an easier time taking over after us.

**Comment by felixwetell** [comment]
This kind of documentation is already in place in the Linda Carlstad Google Drive folder.
